"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-22 00:02:48.822374
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('programme', sa.String(length=80), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('person',
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index('ix_person_telegram', 'person', ['telegram_id'], unique=False)
    op.create_table('enrolment',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('programme', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'cohort_id', name='uq_person_cohort')
    )
    op.create_table('event',
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('actor_person_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=24), nullable=False),
    sa.Column('subject_person_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=80), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['subject_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_occurred', 'event', ['occurred_at'], unique=False)
    op.create_index('ix_event_subject', 'event', ['subject_person_id'], unique=False)
    op.create_index('ix_event_type', 'event', ['event_type'], unique=False)
    op.create_table('flag',
    sa.Column('subject_person_id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subject_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friday_report',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.Column('week_ending', sa.Date(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'week_ending', name='uq_report_week')
    )
    op.create_index('ix_report_week', 'friday_report', ['week_ending'], unique=False)
    op.create_table('intervention',
    sa.Column('subject_person_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['subject_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intervention_status', 'intervention', ['status'], unique=False)
    op.create_table('reporting_line',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', name='uq_reporting_person')
    )
    op.create_table('role_assignment',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'role', name='uq_person_role')
    )
    op.create_table('staff_profile',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('employment_type', sa.String(length=24), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', name='uq_staff_person')
    )
    op.create_table('work_schedule',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=48), nullable=False),
    sa.Column('workdays', sa.String(length=16), nullable=False),
    sa.Column('start_local', sa.String(length=5), nullable=False),
    sa.Column('end_local', sa.String(length=5), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', name='uq_schedule_person')
    )
    op.create_table('mentor_review',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['friday_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentor_review')
    op.drop_table('work_schedule')
    op.drop_table('staff_profile')
    op.drop_table('role_assignment')
    op.drop_table('reporting_line')
    op.drop_index('ix_intervention_status', table_name='intervention')
    op.drop_table('intervention')
    op.drop_index('ix_report_week', table_name='friday_report')
    op.drop_table('friday_report')
    op.drop_table('flag')
    op.drop_index('ix_event_type', table_name='event')
    op.drop_index('ix_event_subject', table_name='event')
    op.drop_index('ix_event_occurred', table_name='event')
    op.drop_table('event')
    op.drop_table('enrolment')
    op.drop_index('ix_person_telegram', table_name='person')
    op.drop_table('person')
    op.drop_table('department')
    op.drop_table('cohort')
    # ### end Alembic commands ###
