"""truth ledger

Revision ID: 0002_truth_ledger
Revises: 0001_baseline
Create Date: 2026-09-22 04:36:26.083624
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002_truth_ledger'
down_revision: str | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('claim_type', sa.String(length=64), nullable=False),
    sa.Column('subject_person_id', sa.Integer(), nullable=True),
    sa.Column('asserted_by_person_id', sa.Integer(), nullable=True),
    sa.Column('asserted_role', sa.String(length=24), nullable=False),
    sa.Column('statement', sa.JSON(), nullable=False),
    sa.Column('provenance_state', sa.String(length=24), nullable=False),
    sa.Column('verification_level', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_ref', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asserted_by_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['subject_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claim_state', 'claim', ['provenance_state'], unique=False)
    op.create_index('ix_claim_subject', 'claim', ['subject_person_id'], unique=False)
    op.create_index('ix_claim_type', 'claim', ['claim_type'], unique=False)
    op.create_table('evidence',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=400), nullable=False),
    sa.Column('submitted_by_person_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_claim', 'evidence', ['claim_id'], unique=False)
    op.create_table('verification',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=48), nullable=False),
    sa.Column('checked_by_person_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('level_reached', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['checked_by_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_claim', 'verification', ['claim_id'], unique=False)
    op.create_table('verification_exception',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewer_person_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['reviewer_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vexception_status', 'verification_exception', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vexception_status', table_name='verification_exception')
    op.drop_table('verification_exception')
    op.drop_index('ix_verification_claim', table_name='verification')
    op.drop_table('verification')
    op.drop_index('ix_evidence_claim', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_claim_type', table_name='claim')
    op.drop_index('ix_claim_subject', table_name='claim')
    op.drop_index('ix_claim_state', table_name='claim')
    op.drop_table('claim')
    # ### end Alembic commands ###
