"""staff join codes

Revision ID: 0004_join_codes
Revises: 0003_checkin
Create Date: 2026-09-22 05:27:01.189500
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0004_join_codes'
down_revision: str | None = '0003_checkin'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_profile', sa.Column('join_code', sa.String(length=12), nullable=True))
    op.add_column('staff_profile', sa.Column('linked', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
    op.create_index('ix_staff_join_code', 'staff_profile', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_staff_join_code', table_name='staff_profile')
    op.drop_column('staff_profile', 'linked')
    op.drop_column('staff_profile', 'join_code')
    # ### end Alembic commands ###
